### PR TITLE
Add CPUID and RDSEED support

### PR DESCRIPTION
**Pull request by nicoonoclaste**
The code is not well-tested yet (I only have access to one box with
RDSEED support, and it's not my laptop), and I didn't add the license
headers yet (but I'm fine with GPLv2, given that it's what you are
using).

Aside from that, the PR should be pretty OK.
Should I squash 7039299 into 4367ddf ?

### CODE REVIEW

**Comment by gebi** [comment]
Hi Nico,

Thx for your patches, they look good!
I'll try to test them this week.

I've not added explicite support for cpuid in the C part till now, but with rdseed it seems to fit better than the systemd hack.

**Comment by nicoonoclaste** [comment]
@gebi Yep.  As mentioned over XMPP, I needed CPUID to check if RDSEED is supported anyhow.

**Comment by equinox0815** [comment]
@nbraud: we can't merge because your changes don't build with GCC (tested with 4.9 and 5). It works with Clang but not GCC.
The changes introducing the problem are in:  7039299

GCC error message:

```
cpuid.c: In function ‘has_rdrand’:
cpuid.c:26:28: error: attempt to free a non-heap object ‘cpuid_rdrand’ [-Werror=free-nonheap-object]
     _cleanup struct cpuid *cpuid_rdrand = cpuid(1);
```

**Comment by nicoonoclaste** [comment]
@equinox0815 Damn.  I will just get rid of the `_cleanup` magic.
PS: Looks like `gcc` doesn't know about the `rdseed` instruction.

**Comment by equinox0815** [comment]
@nbraud: i merged your changes together with some fixes into the branch rdseed. Please base your future changes on this branch.
We still have some issues with the rdseed assembler instruction. The current version works on my laptop (which has rdseed) but apparently doesn't build on travis.
Most probably we need to use the opcode ... take a look at https://www.cryptopp.com/docs/ref/rdrand_8cpp_source.html (Line 422) for an example of how this is done.
